{{ 
    config(
        materialized='ephemeral'
    ) 
}}

with source as (
    select *
    from {{ source('chewybi', 'CUSTOMER_ADDRESSES_FULL_GLOBAL') }}
),

renamed as (
    select
        CUSTOMER_ADDRESS_KEY,
        CUSTOMER_ADDRESS_ID,
        CUSTOMER_ID,
        CUSTOMER_ADDRESS_TYPE,
        CUSTOMER_ADDRESS_STATUS,
        CUSTOMER_ADDRESS_NICKNAME,
        CUSTOMER_ADDRESS_ORGANIZATION_NAME,
        CUSTOMER_ADDRESS_FULL_NAME,
        CUSTOMER_ADDRESS_FIRST_NAME,
        CUSTOMER_ADDRESS_LAST_NAME,
        CUSTOMER_ADDRESS_PERSON_TITLE,
        CUSTOMER_ADDRESS_BUSINESS_TITLE,
        CUSTOMER_ADDRESS_STREET1,
        CUSTOMER_ADDRESS_STREET2,
        CUSTOMER_ADDRESS_STREET3,
        CUSTOMER_ADDRESS_CITY,
        CUSTOMER_ADDRESS_STATE,
        CUSTOMER_ADDRESS_COUNTRY,
        CUSTOMER_ADDRESS_ZIP,
        CUSTOMER_ADDRESS_EMAIL1,
        CUSTOMER_ADDRESS_EMAIL2,
        CUSTOMER_ADDRESS_PHONE1,
        CUSTOMER_ADDRESS_PHONE1_TYPE,
        CUSTOMER_ADDRESS_PHONE2,
        CUSTOMER_ADDRESS_PHONE2_TYPE,
        CUSTOMER_ADDRESS_MOBILE_PHONE1,
        CUSTOMER_ADDRESS_MOBILE_PHONE1_COUNTRY,
        CUSTOMER_ADDRESS_FAX1,
        CUSTOMER_ADDRESS_FAX2,
        CUSTOMER_ADDRESS_TAX_GEOCODE,
        CUSTOMER_ADDRESS_SHIPPING_GEOCODE,
        CUSTOMER_ADDRESS_TIME_CREATED,
        CUSTOMER_ADDRESS_PROFILE_ADDRESS_FLAG,
        CUSTOMER_ADDRESS_PRIMARY_ADDRESS_FLAG,
        CUSTOMER_ADDRESS_FIELD1,
        CUSTOMER_ADDRESS_FIELD2,
        CUSTOMER_ADDRESS_FIELD3,
        CUSTOMER_ADDRESS_QAS_MONIKER,
        CUSTOMER_ADDRESS_QAS_MONIKER_SCORE,
        CUSTOMER_ADDRESS_QAS_STREET1,
        CUSTOMER_ADDRESS_QAS_STREET2,
        CUSTOMER_ADDRESS_QAS_CITY,
        CUSTOMER_ADDRESS_QAS_STATE,
        CUSTOMER_ADDRESS_QAS_ZIP,
        CUSTOMER_ADDRESS_QAS_CARRIER_ROUTE,
        CUSTOMER_ADDRESS_LAST_ORDER_FLAG,
        CUSTOMER_ADDRESS_FIRST_ORDER_FLAG,
        CUSTOMER_ADDRESS_QAS_VERIFICATION_DTTM,
        CUSTOMER_ADDRESS_QAS_VERIFICATION_SOURCE,
        CUSTOMER_ADDRESS_FEDEX_INVOICE_DATE,
        CUSTOMER_ADDRESS_FEDEX_RECIPIENT_ADDRESS1,
        CUSTOMER_ADDRESS_FEDEX_RECIPIENT_ADDRESS2,
        CUSTOMER_ADDRESS_FEDEX_RECIPIENT_CITY,
        CUSTOMER_ADDRESS_FEDEX_RECIPIENT_STATE,
        CUSTOMER_ADDRESS_FEDEX_RECIPIENT_ZIP,
        CUSTOMER_ADDRESS_TYPE_DESCRIPTION,
        CUSTOMER_ADDRESS_STATUS_DESCRIPTION,
        CUSTOMER_ADDRESS_MD5_HASH,
        CUSTOMER_ADDRESS_QAS_MD5_HASH,
        CUSTOMER_ADDRESS_PHONE_MD5_HASH,
        CUSTOMER_ADDRESS_EMAIL_SHA256_HASH_FACEBOOK,
        CUSTOMER_ADDRESS_PHONE_SHA256_HASH_FACEBOOK,
        CUSTOMER_ADDRESS_PHONE_SHA256_HASH_GOOGLE,
        DW_SITE_ID
    from source
)

select *
from renamed
